swagger: "2.0"

info:
  version: 0.0.1
  title: Beacon API
  description: Beacon API to save and retrieve attendee information

schemes:
- http
basePath: /

paths:
  /attendees:
    get:
      description: Return all attendees.
      produces:
      - application/json
      responses:
        200:
          description: Json Array
          schema:
            type: array
            items:
              $ref: '#/definitions/Attendee'
  /attendee:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          description: An attendee data to be saved (6FBBEF7C-F92C-471E-8D5C-470E9B367FDB)
          in: body
          required: true
          schema:
            type: object
            $ref: '#/definitions/Attendee'
      description: Insert an attendee
      responses:
        200:
          description: Attendee is saved successfully
          schema:
            type: string
          examples:
            application/json: |-
              {
                "response": "success"
              }
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Success:
    required:
      - response
    properties:
      response:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  Attendee:
    type: object
    required:
      - beaconID
      - attendeeID
      - timestamp
    properties:
      beaconID:
        type: string
      attendeeID:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      eventID:
        type: string
      eventName:
        type: string
      placeName:
        type: string
      roomName:
        type: string        
      deviceID:
        type: string
      os:
        type: string
      timestamp:
        type: string