swagger: "2.0"

info:
  version: 0.0.1
  title: Beacon API
  description: Beacon API to save and retrieve attendee information

schemes:
- http
basePath: /

paths:
  /attendees/{eventID}:
    get:
      description: |
        Return all event records from devry_beacon.room_attendance_by_event table.
      produces:
        - application/json
      parameters:
        - name: eventID
          in: path
          description: 'event id'
          required: true
          type: string
      responses:
        200:
          description: Json Array
          schema:
            type: array
            items:
              $ref: '#/definitions/Attendee'
  /attendee:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          description: An attendee data to be saved (6FBBEF7C-F92C-471E-8D5C-470E9B367FDB)
          in: body
          required: true
          schema:
            $ref: '#/definitions/AttendeeIn'
      description: Insert an attendee
      responses:
        200:
          description: Attendee is saved successfully
          schema:
            type: string
          examples:
            application/json: |-
              {
                "response": "success"
              }
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Success:
    required:
      - response
    properties:
      response:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  Attendee:
    type: object
    properties:
      eventID:
        type: string
      attendeeID:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      eventName:
        type: string
      eventAddressL1:
        type: string
      eventAddressL2:
        type: string        
      eventCity:
        type: string
      eventState:
        type: string
      eventZip:
        type: string
      eventCountry:
        type: string
      timestamp:
        type: string
  AttendeeIn:
    type: object
    required:
      - attendeeID
      - beaconID
      - eventID
      - eventName
      - timestamp
    properties:
      attendeeID:
        type: string
      beaconID:
        type: string
      eventID:
        type: string
      eventName:
        type: string
      timestamp:
        type: string
      os:
        type: string
      